=== pawellewandowski/TIRT/ComssService/StreamingService.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/StreamingService/" targetNamespace="http://www.example.org/StreamingService/">
    <element name="service" type="tns:ComSSServ"></element>    
    <complexType name="ComSSServ">
    	<sequence>
    		<element name="name" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="address" type="string"></element>
    		<element name="inputs" type="tns:ComSSServInputArray"></element>
    		<element name="outputs" type="tns:ComSSServOutputArray"></element>
    		<element name="cost" type="float"></element>
    		<element name="latency" type="float"></element>
    		<element name="maxInstCount" type="int"></element>
    		<element name="serviceGlobalId" type="string"></element>
    		<element name="classes" type="tns:ComSSServClassArray"></element>
    		<element name="parameters" type="tns:ComSSServParamArray"></element>
    	</sequence>
    </complexType>

    <complexType name="ComSSServInputArray">
    	<sequence>
    		<element name="input" type="tns:ComSSServInput" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ComSSServOutputArray">
    	<sequence>
    		<element name="output" type="tns:ComSSServOutput" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ComSSServInput">
    	<sequence>
    		<element name="id" type="string"></element>
    		<element name="formats" type="tns:ComSSServFormatArray"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ComSSServOutput">
    	<sequence>
    		<element name="id" type="string"></element>
    		<element name="formats" type="tns:ComSSServFormatArray"></element>
    	</sequence>
    </complexType>
    
    <complexType name="ComSSServFormatArray">
    	<sequence>
    		<element name="format" type="tns:ComSSServFormat" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="ComSSServFormat">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="inputRelation" type="string" minOccurs="0"
    			maxOccurs="1">
    		</element>
    		<element name="latency" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="ComSSServClassArray">
    	<sequence>
    		<element name="class" type="string" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="ComSSServParamArray">
    	<sequence>
    		<element name="param" type="string" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>



    <complexType name="ComSSServConversionLatencyArray">
    	<sequence>
    		<element name="conversionLatency" type="tns:ComSSServConversionLatency" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="ComSSServConversionLatency">
    	<sequence>
    		<element name="inputFormats" type="string"></element>
    		<element name="outputFormats" type="string"></element>
    		<element name="latency" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== pawellewandowski/TIRT/ComssService/examples/lower_service/lower_service.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:service xmlns:tns="http://www.example.org/StreamingService/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/StreamingService/ ServiceUtils/StreamingService.xsd ">
  <address>127.0.0.1:13012</address>
  <inputs>
  	<input>
  		<id>1</id>
  		<formats>
  			<format>
  				<name>char_stream</name>
  				<latency>5</latency>
  			</format>
  		</formats>
  	</input></inputs>
  <outputs>
  	<output>
  		<id>2</id>
  		<formats>
  			<format>
  				<name>lower_char_stream</name>
  				<latency>5</latency>
  			</format>
  		</formats>
  	</output>
  	</outputs>
  <cost>2.0</cost>
  <latency>1.5</latency>
  <maxInstCount>1000</maxInstCount>
  <serviceGlobalId>127.0.0.1:13012</serviceGlobalId>
  <classes>
    <class>string_lower</class>
  </classes>
  <parameters/>
</tns:service>
